[package]
name = "radicle_registry_client"
version = "0.1.0"
authors = ["Thomas Scholtes <thomas@monadic.xyz>"]
edition = "2018"

[dependencies]
radicle_registry_runtime = { path = "../runtime" }
radicle_registry_client_common = { path = "../client-common" }
radicle_registry_client_interface = { path = "../client-interface" }
substrate-subxt = { path = "../subxt" }

env_logger = "0.7"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await", "compat"] }
futures01 = { package = "futures", version = "0.1" }
log = "0.4"
parity-scale-codec = "1.0"
tokio = "0.1"

[dependencies.srml-system]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"

[dependencies.srml-support]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"

[dependencies.substrate-primitives]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"

