[package]
name = "radicle_registry_client"
version = "0.1.0"
authors = ["Thomas Scholtes <thomas@monadic.xyz>"]
edition = "2018"

[dependencies]
radicle_registry_runtime = { path = "../runtime" }
substrate-subxt = { path = "../subxt" }

env_logger = "0.7"
futures01 = { package = "futures", version = "0.1" }
futures03 = { package = "futures", version = "0.3", features = ["compat"] }
log = "0.4"
parity-scale-codec = "1.0"
tokio = "0.1"

[dependencies.frame-system]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.frame-support]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.pallet-transaction-payment]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.sp-runtime]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.sp-io]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
