[package]
name = "radicle_registry_runtime"
authors = ["Anonymous"]
edition = "2018"
version = "0.1.0"

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    "sr-primitives/std",
    "sr-io/std",
    "sr-std/std",
    "sr-version/std",
    "srml-aura/std",
    "srml-balances/std",
    "srml-executive/std",
    "srml-sudo/std",
    "srml-support/std",
    "srml-system/std",
    "srml-timestamp/std",
    "srml-transaction-payment/std",
    "substrate-client/std",
    "substrate-consensus-aura-primitives/std",
    "substrate-offchain-primitives/std",
    "substrate-primitives/std",
    "substrate-session/std",
]

[dependencies.codec]
default-features = false
features = ["derive", "full"]
package = "parity-scale-codec"
version = "1.0.0"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0.101"

[dependencies.srml-aura]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default-features = false

[dependencies.substrate-consensus-aura-primitives]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default-features = false

[dependencies.srml-balances]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.substrate-client]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.srml-executive]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
package = "srml-executive"
default_features = false

[dependencies.substrate-offchain-primitives]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default-features = false

[dependencies.substrate-primitives]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.sr-std]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.sr-primitives]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.srml-randomness-collective-flip]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.substrate-session]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default-features = false

[dependencies.srml-sudo]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
package = "srml-sudo"
default_features = false

[dependencies.srml-support]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.srml-system]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.srml-timestamp]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.srml-transaction-payment]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[dependencies.sr-version]
git = "https://github.com/paritytech/substrate"
rev = "acf86cd4b0ad4c45dbba57c2ae323531d5b71264"
default_features = false

[build-dependencies]
substrate-wasm-builder-runner = "1.0.2"

[dev-dependencies]
futures = "0.1"
radicle_registry_memory_client = { path = "../memory-client" }
