[package]
edition = "2018"
name = "radicle-registry-cli"
description = "CLI tools for interacting with the Radicle Registry"
version = "0.0.0"
authors = ["Monadic GmbH <radicle@monadic.xyz>"]
homepage = "https://github.com/radicle-dev/radicle-registry"
documentation = "https://github.com/radicle-dev/radicle-registry"
license = "GPL-3.0-only"
repository = "https://github.com/radicle-dev/radicle-registry"

[dependencies]
radicle-registry-client = { version = "0.0.0", path = "../client" }

futures01 = { package = "futures", version = "0.1" }
hex = "0.4.0"
lazy_static = "1.4"
pretty_env_logger = "0.3.1"
structopt = "0.3"
url = "1.7"

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate"
rev = "4c4ee3d5b91c4c825aef4fde2b096f014a89346a"
