[package]
name = "radicle_registry_cli"
version = "0.1.0"
authors = ["Thomas Scholtes <thomas@monadic.xyz>"]
edition = "2018"

[dependencies]
radicle_registry_client = { path = "../client" }

pretty_env_logger = "0.3.1"
structopt = "0.3"
